version: "3"

services:
  pypi:
    container_name: pypi
    restart: unless-stopped
    network_mode: "host"
    image: "pypi:${TAG:-latest}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    privileged: true
