version: "3"

services:
  neutron-metadata-agent:
    container_name: neutron-metadata-agent
    restart: unless-stopped
    network_mode: "host"
    image: "neutron-metadata-agent:${TAG:-latest}"
    volumes:
      - /etc/environment_config.conf:/etc/environment_config.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/admin.openrc:/etc/admin.openrc:ro
      - log:/var/log/cpcloud/
      - config:/etc/neutron/
      - neutron-metadata-socket:/var/lib/neutron
    privileged: true

volumes:
  config:
    name: neutron-metadata-agent
  log:
    name: cpcloud_logs
  neutron-metadata-socket:
    name: neutron-metadata-socket