version: '2.3'

services:
  cpcloud_web_tty_client:
    container_name: cpcloud_web-tty-client
    restart: always
    network_mode: bridge
    image: "container-web-tty"
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
