version: "2"
services:
  guacd:
    image: guacd:v2
    container_name: cpcloud_guacd
    restart: always
    volumes:
      - /home/convert:/home/convert
      - /var/lib/guacamole:/var/lib/guacamole
      - /home/guacdrive:/tmp/guacdrive
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "4822:4822"
    networks:
      bridge_network:
        ipv4_address: 172.30.0.149
  guacamole:
    image: guacamole:v3.1
    container_name: cpcloud_guacamole
    restart: always
    environment:
      - GUACD_PORT=4822
      - GUACD_HOSTNAME=cpcloud_guacd
      - MYSQL_PORT=3306
      - MYSQL_USER=guacamole
      - MYSQL_PASSWORD=guacamole
      - MYSQL_DATABASE=guacamole
      - MYSQL_HOSTNAME=controller
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/hosts:/etc/hosts:ro
    links:
      - "guacd:guacd"
    external_links:
      - "mariadb:mariadb"
    ports:
      - "9200:8080"
    networks:
      - bridge_network

networks:
  bridge_network:
    external: true
