version: "3"

services:
  rabbitmq:
    container_name: rabbitmq
    restart: unless-stopped
    network_mode: "host"
    image: "rabbitmq:${TAG:-latest}"
    volumes:
      - /etc/environment_config.conf:/etc/environment_config.conf
      - /etc/localtime:/etc/localtime:ro
      - log:/var/log/cpcloud/
      - data:/var/lib/rabbitmq
      - /etc/cpcloud/rabbitmq/:/etc/rabbitmq/:rw

volumes:
  data:
    name: rabbitmq
  log:
    name: cpcloud_logs