version: "3"

services:
  neutron-server:
    container_name: neutron-server
    restart: unless-stopped
    network_mode: "host"
    image: "neutron-server:${TAG:-latest}"
    volumes:
      - /etc/environment_config.conf:/etc/environment_config.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/admin.openrc:/etc/admin.openrc:ro
      - /opt/pip/v:/opt/pip/v
      - log:/var/log/cpcloud/
      - config:/etc/neutron/

volumes:
  config:
    name: neutron-server
  log:
    name: cpcloud_logs