version: "3"

services:
  cinder-api:
    container_name: cinder-api
    restart: unless-stopped
    network_mode: "host"
    image: "cinder-api:${TAG:-latest}"
    volumes:
      - /etc/environment_config.conf:/etc/environment_config.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/admin.openrc:/etc/admin.openrc:ro
      - log:/var/log/cpcloud/
      - config:/etc/cinder/

volumes:
  config:
    name: cinder-api
  log:
    name: cpcloud_logs