version: "3"

services:
  openvswitch-db-server:
    container_name: openvswitch-db-server
    restart: unless-stopped
    network_mode: "host"
    image: "openvswitch-db-server:${TAG:-latest}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/admin.openrc:/etc/admin.openrc:ro
      - /etc/environment_config.conf:/etc/environment_config.conf
      - /lib/modules:/lib/modules:ro
      - /run/openvswitch:/run/openvswitch:shared
      - log:/var/log/cpcloud/
      - data:/var/lib/openvswitch

volumes:
  log:
    name: cpcloud_logs
  data:
    name: openvswitch-db-server
